### ISSUE TITLE
Prepare Jakarta JSON Binding for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsonb-api#158]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Submit a PR to jakartaee/specifications repository
- [ ] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by scottkurz** [comment]
Was looking (for batch) for examples linking to the EFSL license from Javadoc, and noticed you have the files in source but not  zipped up into the JAR.   

You could, e.g. add to the plugin config
`<docfilessubdirs>true</docfilessubdirs>`
like [here](https://github.com/scottkurz/jsonb-api/blob/84db1181e89dfd787ca1a8fd22ed60220358dd27/api/pom.xml#L386-L427).    

Or if there's a better way I'll keep watching.

**Comment by m0mus** [comment]
@scottkurz It's fixed

**Comment by m0mus** [comment]
Reopening because new tasks were added.

**Comment by m0mus** [comment]
Jakarta EE API PR: https://github.com/eclipse-ee4j/jakartaee-api/pull/11
